# Generated by Django 3.0.2 on 2021-05-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ditrict',
            new_name='district',
        ),
    ]
