# Generated by Django 3.0.2 on 2021-05-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregistration', '0002_auto_20210501_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.district')),
            ],
        ),
    ]
