# Generated by Django 3.0.2 on 2021-05-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregistration', '0003_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='empbasicinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('joiningdate', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('Permanent', 'Permanent'), ('Trainee', 'Trainee')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='empdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='empdesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='empsalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicsalary', models.FloatField()),
                ('medical', models.FloatField()),
                ('houserent', models.FloatField()),
                ('others', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.empbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='empeducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Bachelor', 'Bachelor')], max_length=10)),
                ('institute', models.CharField(max_length=100)),
                ('passingyear', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.empbasicinfo')),
            ],
        ),
        migrations.AddField(
            model_name='empbasicinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.empdepartment'),
        ),
        migrations.AddField(
            model_name='empbasicinfo',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.empdesignation'),
        ),
        migrations.AddField(
            model_name='empbasicinfo',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.district'),
        ),
        migrations.AddField(
            model_name='empbasicinfo',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregistration.thana'),
        ),
    ]
